services:
  app:
    build:
      context: .   # change to . if your Dockerfile is in the same folder as this compose file
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      # Use service names, and match mysql db/user/pass below
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/prescriptions

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"   # change to "3307:3306" if 3306 is already in use on your host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27018:27017" # change to "27018:27017" if needed
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
